<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.asd-europe.org/s3000l/validValues" targetNamespace="http://www.asd-europe.org/s3000l/validValues" version="001-00">
	<xsd:annotation>
		<xsd:documentation>Issue number: 2.0</xsd:documentation>
		<xsd:documentation>Issue date: 2021-04-30</xsd:documentation>
		<xsd:documentation>Valid values release number: 001-00</xsd:documentation>
		<xsd:documentation>Valid values release date: 2021-04-30</xsd:documentation>
		<xsd:documentation>URL: http://www.s3000l.org</xsd:documentation>
		<xsd:documentation>Copyright:
                Copyright file structure (c) 2016-2021 by AeroSpace and Defence Industries Associations of Europe (ASD).
                Copyright enumerated codes (c) 1978 by International Standards Organization (ISO) as per ISO 4217.
                
                Limitations of Liability:
                
                1.  This material is provided 'As Is' and neither ASD nor any person who has contributed to the creation, revision or maintenance of the material makes any representations or warranties, express or implied, including but not limited to, warranties of merchantability or fitness for any particular purpose.
                2.  Neither ASD nor any person who has contributed to the creation, revision or maintenance of this material shall be liable for any direct, indirect, special or consequential damages or any other liability arising from any use of this material.
                3.  Revisions to this document may occur after its issuance.  The user is responsible for determining if revisions to the material contained in this document have occurred and are applicable.
            </xsd:documentation>
	</xsd:annotation>
	<!-- ___________________________________________________________________________________________________ -->
	<!-- Source ISO 4217  -->
	<xsd:simpleType name="currencyUnit">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="AED">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unitedArabEmiratesDirham</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AFN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:afghanAfghani</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ALL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:albanianLek</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AMD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:armenianDram</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ANG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:netherlandsAntilleanGuilder</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AOA">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:angolanKwanza</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ARS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:argentinePeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AUD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:australianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AWG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:arubanFlorin</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="AZN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:azerbaijaniManat</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BAM">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bosniaAndHerzegovinaConvertibleMark</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BBD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:barbadosDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BDT">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bangladeshiTaka</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BGN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bulgarianLev</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BHD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bahrainiDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BIF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:burundianFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BMD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bermudianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BND">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bruneiDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BOB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:boliviano</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BOV">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bolivianMvdol</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BRL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:brazilianReal</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BSD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bahamianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BTN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:bhutaneseNgultrum</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BWP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:botswanaPula</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BYR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:belarusianRuble</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="BZD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:belizeDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CAD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:canadianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CDF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:congoleseFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CHE">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:wirEuro</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CHF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:swissFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CHW">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:wirFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CLF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unidadDeFomento</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CLP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:chileanPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CNY">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:chineseYuan</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="COP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:colombianPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="COU">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unidadDeValorReal</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CRC">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:costaRicanColon</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CUC">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cubanConvertiblePeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CUP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cubanPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CVE">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:capeVerdeEscudo</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="CZK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:czechKoruna</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DJF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:djiboutianFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DKK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:danishKrone</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DOP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:dominicanPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DZD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:algerianDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="EGP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:egyptianPound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ERN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:eritreanNakfa</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ETB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:ethiopianBirr</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="EUR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:euro</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="FJD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:fijiDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="FKP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:falklandIslandsPound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GBP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:poundSterling</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GEL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:georgianLari</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GHS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:ghanaianCedi</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GIP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:gibraltarPound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GMD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:gambianDalasi</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GNF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:guineanFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GTQ">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:guatemalanQuetzal</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="GYD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:guyaneseDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="HKD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:hongKongDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="HNL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:honduranLempira</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="HRK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:croatianKuna</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="HTG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:haitianGourde</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="HUF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:hungarianForint</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="IDR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:indonesianRupiah</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ILS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:israeliNewShekel</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="INR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:indianRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="IQD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:iraqiDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="IRR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:iranianRial</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ISK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:icelandicKrona</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="JMD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:jamaicanDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="JOD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:jordanianDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="JPY">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:japaneseYen</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KES">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:kenyanShilling</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KGS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:kyrgyzstaniSom</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KHR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cambodianRiel</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KMF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:comoroFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KPW">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:northKoreanWon</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KRW">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:southKoreanWon</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KWD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:kuwaitiDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KYD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:caymanIslandsDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="KZT">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:kazakhstaniTenge</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LAK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:laoKip</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LBP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:lebanesePound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LKR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:sriLankanRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LRD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:liberianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LSL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:lesothoLoti</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="LYD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:libyanDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MAD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:moroccanDirham</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MDL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:moldovanLeu</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MGA">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:malagasyAriary</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MKD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:macedonianDenar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MMK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:myanmarKyat</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MNT">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mongolianTugrik</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MOP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:macanesePataca</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MRO">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mauritanianOuguiya</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MUR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mauritianRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MVR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:maldivianRufiyaa</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MWK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:malawianKwacha</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MXN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mexicanPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MXV">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mexicanUnidadDeInversion</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MYR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:malaysianRinggit</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="MZN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:mozambicanMetical</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NAD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:namibianDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NGN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:nigerianNaira</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NIO">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:nicaraguanCordoba</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NOK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:norwegianKrone</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NPR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:nepaleseRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="NZD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:newZealandDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="OMR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:omaniRial</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PAB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:panamanianBalboa</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PEN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:peruvianNuevoSol</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PGK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:papuaNewGuineanKina</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PHP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:philippinePeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PKR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:pakistaniRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PLN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:polishZloty</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PYG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:paraguayanGuarani</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="QAR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:qatariRiyal</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RON">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:romanianLeu</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RSD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:serbianDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RUB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:russianRuble</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RWF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:rwandanFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SAR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:saudiRiyal</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SBD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:solomonIslandsDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SCR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:seychellesRupee</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SDG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:sudanesePound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SEK">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:swedishKrona</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SGD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:singaporeDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SHP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:saintHelenaPound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SLL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:sierraLeoneanLeone</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SOS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:somaliShilling</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SRD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:surinameseDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SSP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:southSudanesePound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="STD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:saoTomeAndPrincipeDobra</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SYP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:syrianPound</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SZL">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:swaziLilangeni</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="THB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:thaiBaht</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TJS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:tajikistaniSomoni</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TMT">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:turkmenistaniManat</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TND">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:tunisianDinar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TOP">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:tonganPaanga</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TRY">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:turkishLira</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TTD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:trinidadAndTobagoDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TWD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:newTaiwanDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TZS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:tanzanianShilling</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="UAH">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:ukrainianHryvnia</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="UGX">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:ugandanShilling</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="USD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unitedStatesdollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="USN">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unitedStatesDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="USS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:unitedStatesDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="UYI">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:uruguayPesoEnUnidadesIndexadas</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="UYU">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:uruguayanPeso</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="UZS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:uzbekistanSom</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="VEF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:venezuelanBolivar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="VND">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:vietnameseDong</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="VUV">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:vanuatuVatu</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="WST">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:samoanTala</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XAF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cfaFrancBeac</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XAG">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:silver</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XAU">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:gold</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XBA">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:europeanCompositeUnit</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XBB">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:europeanMonetaryUnit</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XBC">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:europeanUnitOfAccount9</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XBD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:europeanUnitOfAccount17</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XCD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:eastCaribbeanDollar</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XDR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:specialDrawingRights</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XFU">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:uICFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XOF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cfaFrancBceao</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XPD">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:palladium</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XPF">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:cfpFranc</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XPT">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:platinum</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XSU">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:sucre</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XTS">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:codeReservedForTestingPurposes</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XUA">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:adbUnitOfAccount</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="XXX">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:noCurrency </xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="YER">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:yemeniRial</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ZAR">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:southAfricanRand</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ZMW">
				<xsd:annotation>
					<xsd:appinfo>ISO4217:zambianKwacha</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
